verbose logging for travis build

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -38,6 +38,11 @@ for repo in ${SERVICES[@]}; do
     # "script/setup is typically run after an initial clone"
     cd $top/$service
     log=$top/log/$service.setup.log
-    echo -e "\tscript/setup: Output at $log";
-    script/setup > $log 2>&1 || echo "⚠️  Setup failed for $service"
+    if [ -n "${ATAT_STACK_VERBOSE+set}" ]; then
+      echo -e "\tscript/setup: Starting output for $service";
+      script/setup
+    else
+      echo -e "\tscript/setup: Output at $log";
+      script/setup > $log 2>&1 || echo "⚠️  Setup failed for $service"
+    fi
 done
