Reduce script/bootstrap verbosity

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -22,11 +22,11 @@ for repo in ${SERVICES[@]}; do
 
     cd $top
     echo "Cloning $service at $version"
-    curl -sSL https://github.com/dod-ccpo/$service/archive/$version.tar.gz | tar xvz
+    curl -sSL https://github.com/dod-ccpo/$service/archive/$version.tar.gz | tar xz
     mv $service-$version $service
     # "script/setup is typically run after an initial clone"
     cd $top/$service
     log=$top/log/$service.setup.log
-    echo "Writing to $log";
-    script/setup 2>&1 | tee $log || echo "Setup failed for $service"
+    echo -e "\tscript/setup: Output at $log";
+    script/setup > $log 2>&1 || echo "⚠️  Setup failed for $service"
 done
